### ISSUE TITLE
Regarding the issue Rams opened in LMMS

### ISSUE THREAD

**Issue by Monospace-V** [TheRamsWay/pw_2021#1]
@TheRamsWay This is off-topic, but I want to ask, in your comment `https://github.com/LMMS/lmms/issues/6305#issuecomment-1037231803` which song is that in the MIDI file? I like it, but I do not know it.
So sorry for the inconvenience caused. I would like to know what track this is and have no way of finding out. A source or song name would be appreciated.
Thanks!

**Comment by TheRamsWay** [comment]
No problem! It's [Giratina's battle theme](https://www.youtube.com/watch?v=iy4WUVI7Lrw) from Pokémon Platinum, the audio file was extracted from the game's ROM and converted to MIDI with Nitro Studio 2.

**Comment by Monospace-V** [comment]
Thanks! I'll check it out. Crazy track, that.
